c331033 김윤진

# 데이터유형

In [11]:
x_value = 12345

print(f'{x_value = }\n{type(x_value) = }')

x_value = 12345
type(x_value) = <class 'int'>


In [12]:
x_str = 'abcde'

print(f'{x_str = }\n{type(x_str) = }')

x_str = 'abcde'
type(x_str) = <class 'str'>


In [13]:
x_list = [x_str, x_value]

print(f'{x_list = }\n{type(x_list) = }')

x_list = ['abcde', 12345]
type(x_list) = <class 'list'>


In [14]:
x_tuple = (x_str, x_value)

print(f'{x_tuple = }\n{type(x_tuple)=}')

x_tuple = ('abcde', 12345)
type(x_tuple)=<class 'tuple'>


In [15]:
x_dict = {'name': 'Chunghun Ha', 'id':68490}

print(f'{x_dict = }\n{type(x_dict) = }')


x_dict = {'name': 'Chunghun Ha', 'id': 68490}
type(x_dict) = <class 'dict'>


In [16]:
x_none = None

print(f'{x_none = }\n{type(x_none) = }')

x_none = None
type(x_none) = <class 'NoneType'>


# 추가학습 내용

In [17]:
var_x = 12345
print(f'{var_x= }')
print(f'{type(var_x)=}')

var_x= 12345
type(var_x)=<class 'int'>


var_x의 유형은 클래스(class) 'int'임. 즉, 객체(object)임

# 추가학습 내용 끝

In [18]:
print(dir(x_value))

['__abs__', '__add__', '__and__', '__bool__', '__ceil__', '__class__', '__delattr__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floor__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__le__', '__lshift__', '__lt__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rrshift__', '__rshift__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__trunc__', '__xor__', 'as_integer_ratio', 'bit_count', 'bit_length', 'conjugate', 'denominator', 'from_bytes', 'imag', 'is_integer', 'numerator', 'real', 'to_bytes']


In [19]:
print(f'{x_value.real = }')

print(f'{x_value.bit_length() = }')

x_value.real = 12345
x_value.bit_length() = 14


In [20]:
x_list = ['abcde', 12345]

print(f'Before: {x_list = }')

x_list[1] = 'fghij'

print(f'After : {x_list = }')


Before: x_list = ['abcde', 12345]
After : x_list = ['abcde', 'fghij']


In [21]:
x_dict = {'name': 'Chunghun Ha', 'id':67890}

print(f'Before: {x_dict = }')

x_dict['name'] = 'Gildong Hong'

print(f'After : {x_dict = }')


Before: x_dict = {'name': 'Chunghun Ha', 'id': 67890}
After : x_dict = {'name': 'Gildong Hong', 'id': 67890}


In [22]:
x_str = 'abcde'

print(f'Before: {x_str = }')

try:
    x_str[1] = '2'
except TypeError as e:
    print(f'Error: {e}')

print(f'After : {x_str = }')

Before: x_str = 'abcde'
Error: 'str' object does not support item assignment
After : x_str = 'abcde'


In [23]:
x_tuple = ('abcde', 12345)

print(f'Before: {x_tuple = }')

try:
    x_tuple[1] = 'fghij'
except TypeError as e:
    print(f'Error : {e}')

print(f'After : {x_tuple =}')




Before: x_tuple = ('abcde', 12345)
Error : 'tuple' object does not support item assignment
After : x_tuple =('abcde', 12345)


In [24]:
var_x = 12345

print(f'{var_x}는 {type(var_x)}', end='\n'+'-'*30+'\n')

var_y = float(var_x)

print(f'{var_y}는 {type(var_y)}', end='\n'+'-'*30+'\n')

var_y = str(var_x)

print(f'{var_y}는 {type(var_y)}', end='\n'+'-'*30+'\n')

var_y = bool(var_x)

print(f'{var_y}는 {type(var_y)}')

12345는 <class 'int'>
------------------------------
12345.0는 <class 'float'>
------------------------------
12345는 <class 'str'>
------------------------------
True는 <class 'bool'>


# 추가학습 내용

In [25]:
'Abc' + "Abc"

'AbcAbc'

문자열은 +를 붙이기로 인식

In [26]:
123+456

579

숫자는 +를 더하기로 인식

In [27]:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

리스트는 덧셈이 요소들을 연결하는것으로 인식

In [28]:
(1,2,3)+(4,5,6)

(1, 2, 3, 4, 5, 6)

튜플은 덧셈이 요소들을 연결하는것으로 인식

In [29]:
(1,2,3)+(1,2,3)

(1, 2, 3, 1, 2, 3)

튜플은 덧셈이 요소들을 연결하는것으로 인식

{1,2,3}+{1,2,3}은 에러가 난다. 집합은 덧셈이 불가능하기 때문이다.

In [30]:
['A','b','c']*3

['A', 'b', 'c', 'A', 'b', 'c', 'A', 'b', 'c']

['A', 'b', 'c']라는 리스트를 3번 반복한다.

In [31]:
3.0*2

6.0

숫자 3.0을 2배 곱하는 연산이다.

In [32]:
'Abc'*10

'AbcAbcAbcAbcAbcAbcAbcAbcAbcAbc'

문자열 'Abc'를 10번 반복하는 연산이다.

In [33]:
bool(0)

False

불리언에서 숫자인 경우 0이면 false다.

In [34]:
bool(0.0)

False

불리언에서 숫자인 경우 0이면 false다.

In [35]:
bool(0.1)

True

불리언에서 숫자인 경우 0이 아니면 true다.

In [36]:
bool(-0.1)

True

불리언에서 숫자인 경우 0이 아니면 true다.

In [37]:
bool('')

False

불리언에서 원소가 없으면 false다.

In [38]:
bool(' ')

True

불리언에서 원소가 있으면 true다.

In [39]:
bool([0])

True

리스트 [0]는 요소가 하나 있기 때문에 0을 포함하고 있더라도 True이다.

In [40]:
bool([])

False

리스트에 요소가 없기 때문에 False이다.

In [41]:
bool(())

False

튜플에 요소가 없기 때문에 False이다.

In [42]:
bool((0))

False

0은 원소로서의 0이 아니라 숫자로서의 0이기 때문에 False이다.

In [43]:
bool((0,))

True

콤마로 인해 튜플이어서 0이란 원소를 갖기에 True이다.

In [44]:
str(12345)

'12345'

str() 함수는 객체를 문자열 형식으로 변환하는 함수이다. 숫자 12345를 str() 함수에 전달하면, 숫자가 문자열 '12345'로 변환된다.

In [45]:
str(12345.0)

'12345.0'

str() 함수는 주어진 객체를 문자열 형식으로 변환하는 함수이다. 실수 12345.0을 str() 함수에 전달했기 때문에, 12345.0이 문자열로 변환된다.

In [46]:
str([1,2,3])

'[1, 2, 3]'

리스트 [1, 2, 3]을 str() 함수에 전달하면, 리스트를 그 자체의 문자열로 변환된다.

float([1,2,3])는 에러가 난다. str이나 숫자만 가능하다. list나 튜플은 안된다.

In [47]:
float('123.45')

123.45

문자열 '123.45'를 실수(float)로 변환하는 연산이다. float() 함수에 전달하면 실수 123.45로 변환된다.

float('z123.45') float() 함수는 문자열이 유효한 실수 형식일 경우에만 이를 실수로 변환할 수 있다. 

# 추가학습 내용 끝

In [48]:
var_x = range(-10, 0, 2)

print(f'(var_x)는 {type(var_x)}', end='\n'+'-'*30+'\n')

var_y = list(var_x)

print(f'{var_y}는 {type(var_y)}', end='\n'+'-'*30+'\n')

var_y = tuple(var_x)

print(f'{var_y}는 {type(var_y)}', end='\n'+'-'*30+'\n')

var_y = set(var_x)

print(f'{var_y}는 {type(var_y)}')

(var_x)는 <class 'range'>
------------------------------
[-10, -8, -6, -4, -2]는 <class 'list'>
------------------------------
(-10, -8, -6, -4, -2)는 <class 'tuple'>
------------------------------
{-10, -8, -6, -4, -2}는 <class 'set'>


In [49]:
var_x = "abcdab"

print(f"{var_x}는 {type(var_x)}", end='\n'+'-'*30+'\n')

var_y = list(var_x)
print(f"{var_y}는 {type(var_y)}", end='\n'+'-'*30+'\n')

var_y = tuple(var_x)
print(f"{var_y}는 {type(var_y)}", end='\n'+'-'*30+'\n')

var_y = set(var_x)
print(f"{var_y}는 {type(var_y)}", end='\n'+'-'*30+'\n')


abcdab는 <class 'str'>
------------------------------
['a', 'b', 'c', 'd', 'a', 'b']는 <class 'list'>
------------------------------
('a', 'b', 'c', 'd', 'a', 'b')는 <class 'tuple'>
------------------------------
{'b', 'c', 'd', 'a'}는 <class 'set'>
------------------------------


# 추가학습 내용

In [50]:
for i in [1,2,3,4,5]:
    print (i)

1
2
3
4
5


for 루프를 사용하여 리스트 [1, 2, 3, 4, 5]의 각 요소를 하나씩 출력하는 코드이다.

In [51]:
for i in (1,2,3,4,5):
    print (i)

1
2
3
4
5


for 루프를 사용하여 튜플 (1,2,3,4,5)의 각 요소를 하나씩 출력하는 코드이다.

In [52]:
for i in {1,2,3,4,5}:
    print (i)

1
2
3
4
5


for 루프를 사용하여 집합 {1,2,3,4,5}의 각 요소를 하나씩 출력하는 코드이다.

In [53]:
for i in {5,4,3,2,1,2,3,4,5}:
    print (i)

1
2
3
4
5


집합이기에 중복을 없애고 순서가 의미없다.

In [54]:
for i in [5,4,3,2,1,2,3,4,5]:
    print (i)

5
4
3
2
1
2
3
4
5


for 루프를 사용하여 리스트 [5, 4, 3, 2, 1, 2, 3, 4, 5]의 각 요소를 하나씩 출력하는 코드이다.

a=3
 b=4
a+b는 에러가 난다. 인덴트를 하면 안되기 때문이다.

In [55]:
a=3; b=4
a+b

7

In [56]:
a=3; b=4; a+b

7

;는 줄바꿈을 하지 않아도 한줄에 쓸 수 있도록 도와준다.

In [57]:
list(range(2, 10,3))

[2, 5, 8]

2부터 10전까지 상승폭 3으로 출력하는 코드이다.

In [58]:
list(range(29, 10, -3))

[29, 26, 23, 20, 17, 14, 11]

29부터 10전까지 3씩 감소하는 숫자를 출력하는 코드이다.

In [59]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

0부터 9까지의 숫자를 생성하고, 이를 리스트로 변환하는 코드이다.

In [60]:
list(range(2, 10))

[2, 3, 4, 5, 6, 7, 8, 9]

 2부터 9까지의 숫자를 생성하고 이를 리스트로 변환하는 코드이다.

list(range(29, 10, -3.5))는 에러이다. range() 함수는 정수 값만을 사용할 수 있기 때문이다.

list(range(29.4, 10, -3))는 에러이다. range() 함수는 정수 값만을 사용할 수 있기 때문이다.